# Generated by Django 3.0.5 on 2020-04-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_control', '0003_auto_20200417_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
