# Generated by Django 3.0.5 on 2020-04-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_control', '0006_auto_20200418_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='quest',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
