# Generated by Django 3.0.5 on 2020-04-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_control', '0007_auto_20200418_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='start',
        ),
    ]
