# Generated by Django 3.0.5 on 2020-04-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_control', '0008_remove_quest_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
