# Generated by Django 3.0.5 on 2020-04-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_control', '0009_notice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
